steps:
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '.'
      ]
    dir: './cloud-run'

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      ]
    dir: './cloud-run'

  - id: 'deploy image'
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '--region=asia-east1',
        '--platform=managed',
        '--cpu=1',
        '--memory=128Mi',
        '--max-instances=1',
        '--port=8080',
      ]
    dir: './cloud-run'

substitutions:
  _SERVICE_NAME: 'pubsub-notification'
